### ISSUE TITLE
What is the import name

### ISSUE THREAD

**Issue by gautam0826** [ddm7018/Elo#1]
Sorry for the dumb question but what do I type to import this? I've downloaded it using pip and can't seem to import it. Have tried variations of elo, elo_sports, elo-sports, and eloSports and none work for me

**Comment by ddm7018** [comment]
Not a dumb question at all. I checked out and had similar issues. I am working to resolve but in meantime you can download the .py files found in the elo-sports folder here.  Sorry for the inconvenience.

**Comment by ddm7018** [comment]
Package has been updated and renamed.
pip install elosports --update
from elosports import elo
